"""add pending ticket uniqueness

Revision ID: 27176a233e7c
Revises: 9d8927f130c1
Create Date: 2026-09-26 13:46:08.209684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27176a233e7c'
down_revision: Union[str, Sequence[str], None] = '9d8927f130c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_tickets_pending_order_action', 'tickets', ['order_id', 'action'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tickets_pending_order_action', table_name='tickets', postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###
