"""add user long term memories

Revision ID: 7019799045c6
Revises: e8267b4ac0a4
Create Date: 2026-09-28 14:50:34.787039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7019799045c6'
down_revision: Union[str, Sequence[str], None] = 'e8267b4ac0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memories',
    sa.Column('memory_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_thread_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('memory_id'),
    sa.UniqueConstraint('user_id', 'memory_type', 'source_id', name='uq_user_memories_user_type_source')
    )
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.create_index('ix_user_memories_user_type', 'user_memories', ['user_id', 'memory_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_memories_user_type', table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_table('user_memories')
    # ### end Alembic commands ###
