"""add policy order status filter

Revision ID: e8267b4ac0a4
Revises: e81f55b5ecbb
Create Date: 2026-09-27 18:13:18.098948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8267b4ac0a4'
down_revision: Union[str, Sequence[str], None] = 'e81f55b5ecbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_documents', sa.Column('applicable_order_status', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_policy_documents_applicable_order_status'), 'policy_documents', ['applicable_order_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_documents_applicable_order_status'), table_name='policy_documents')
    op.drop_column('policy_documents', 'applicable_order_status')
    # ### end Alembic commands ###
